app/routes/profile_routes.py
'''Routes for profile creation'''

from flask import Blueprint, redirect, render_template, request,session, flash, current_app, url_for
from app.profile.profile import ProfileHandling
from app.profile.settings import SettingsHandling
from app.auth.authentication import login_required
bp = Blueprint('profile_blueprint', __name__, url_prefix='/profile')

@bp.route("/create", methods=["GET", "POST"])
def create_profile():
    '''Endpoint for creating a profile'''
    if request.method == 'POST':
        username = request.form['profileUsername']
        email = request.form['profileEmail']
        password = request.form['profilePassword']
        prof = ProfileHandling()
        user = prof.add_user(username,password,email)
        # User created, so let's add default settings
        settings_obj = SettingsHandling()
        if user:
            settings_obj.add_defaults(user.get('users_id'))
            #return_value = render_template('profile_created.html', user = user)
            flash("Your profile was created. Please login")
            return_value = redirect(url_for('auth_blueprint.login'))
        else:
            return_value = render_template("profile_creation_failed.html")
    else:
        return_value = render_template('create_profile.html')
    return return_value

@bp.route("/info")
def profile_info():
    '''Endpoint to inform about user info'''
    return "This is the profile info endpoint"

@bp.route("/me")
@login_required
def profile():
    '''Endpoint to show information about your own profile'''
    prof = ProfileHandling()
    users_id = session['user_id']
    userdata = prof.get_user_data(users_id)
    return render_template("profile_me.html", userdata=userdata)

@bp.route("/update", methods=["POST"])
def update_profile():
    '''Endpoint for updating a profile'''
    # Mock userdata for now
    prof = ProfileHandling()
    users_id = session['user_id']
    userdata = prof.get_user_data(users_id)
    #userdata = {'email': "", 'username': ""}
    new_email = request.form['profileEmail']
    if prof.update_profile(users_id,new_email):
        flash("Profile updated")
    else:
        flash("Profile update failed")
    return render_template("profile_me.html", userdata = userdata)

@bp.route("/changePassword", methods=['GET','POST'])
@login_required
def change_password():
    '''Endpoint for the change password form'''
    if request.method == 'GET':
        return_is = render_template("change_password.html")
    else:
        if request.form['new_password_1'] == request.form['new_password_2']:
            new_password = request.form['new_password_1']
            users_id = session['user_id']
            prof = ProfileHandling()
            email = prof.get_email_by_uuid(users_id)
            if prof.update_password(users_id,email,request.form['current_password'],new_password):
                flash("Password changed")
                return_is = render_template("change_password.html")
        else:
            flash("Passwords don't match")
            return_is = render_template("change_password.html")
    return return_is

@bp.route("/settings", methods=['GET','POST'])
@login_required
def profile_settings():
    '''Endpoint for a user to edit settings'''
    settings_obj = SettingsHandling()
    settings = settings_obj.get_settings(session['user_id'])
    if request.method == 'POST':
        for i in range(1,8):
            current_key = f'workdayLength{i}Hour'
            current_value = request.form[current_key]
            updated = check_and_update(settings_obj, settings, current_key, current_value)
            if updated:
                current_app.logger.debug(f"{current_key} updated to {current_value}")
            current_key = f'workdayLength{i}Minutes'
            current_value = request.form[current_key]
            updated = check_and_update(settings_obj, settings, current_key, current_value)
            if updated:
                current_app.logger.debug(f"{current_key} updated to {current_value}")
    else:
        if len(settings) == 0:
            settings_obj.add_defaults(session['user_id'])
        settings = settings_obj.get_settings(session['user_id'])
    workweek_day_lengths = settings_obj.get_workweek_day_lengths(session['user_id'])
    return render_template(
        "profile_settings.html",
         settings = settings,
          workday_lengths = workweek_day_lengths
          )

def check_and_update(settings_obj, settings, current_key, current_value):
    '''Checks if the value was updated and needs to be comitted to the database'''
    updated = False
    if current_value != settings.get(current_key):
        updated = settings_obj.add_setting(session['user_id'],current_key,current_value)
    elif current_value == 0:
        # Handle if the value is zero
        updated = settings_obj.add_setting(session['user_id'],current_key,current_value)
    return updated

app/templates/change_password.html
{% extends "header.html" %}
{% block profile %}
<div class="container">
    <br/><br/><br/>
    <div class="card" style="width: 50rem;">
        <div class="card-body">
            <h5 class="card-title">Change password</h5>
            <form action="/profile/changePassword" method="POST"> 
                <div class="form-group">
                    <label for="current_password">Current Password</label>
                    <input type="password" class="form-control" id="current_password" placeholder="Current Password" name="current_password">
                </div>
                <div class="form-row">
                    <div class="col">
                        <label for="new_password_1">New password</label>
                        <input type="password" class="form-control" id="new_password_1" placeholder="New Password" name="new_password_1">
                    </div>
                    <div class="col">
                        <label for="new_password_2">Repeat new password</label>
                        <input type="password" class="form-control" id="new_password_2" placeholder="New Password" name="new_password_2">
                        
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">

                    </div>
                    <div class="col">
                        <button type="submit" class="btn btn-success float-right" >Change password</button>    
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} 

app/templates/header.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/@popperjs/core@2"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        
  <script lang="javascript">
    $(document).ready(function(){
    $('.toast').toast('show');
  });</script>
  <link rel="stylesheet" href="/static/css/background.css">
  <title>Do Time Me!</title>
</head>
<body>
{% include 'navbar.html' %}
{% block body %}

{% block profile %}{% endblock %}

{% endblock %}

<div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
  <div class="toast-header">
    <i class="bi-server"></i>
    <strong class="mr-auto">info box</strong>
    <small>Just for info</small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="toast-body">
    Hostname: {{ hostname }}<br/>
    Version: {{ version }}
  </div>
</div>
<footer>Footer..</footer>
</body>
</html>

app/templates/health.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>Do Time Me - Healthprobe</title>
</head>
<body>
  {{ healthString }}
</body>
</html>

app/templates/home.html
{% extends "header.html" %}
{% block body %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="form-group alert alert-success" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}
{% endwith %}
<br/>
<div class="container align-items-center justify-content-center">
    <div class="card mb-3 justify-content-center" style="max-width: 800px;">
        <div class="row g-0 justify-content-center">
        <div class="col-md-4">
            <img src="/images/frontpage_welcome.jpg" class="brand_logo" alt="Logo" height="159" width="239">
            <p class="card-text"><small class="text-muted">Photo by <a href="https://unsplash.com/@anniespratt?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Annie Spratt</a> on <a href="https://unsplash.com/s/photos/team?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a></small></p>
        </div>
        <div class="col-md-8 justify-content-center">
            <div class="card-body justify-content-center">
            <h5 class="card-title">Welcome to doTime! It will be awesome!!</h5>
            <p class="card-text">
                <p><em>DoTime aims to be an easy to use time registration for you. </em><br/>A way to keep an eye on the amount of hours you put in your workplace.<br/><br/>
                Whether you want to feel good when you leave for the weekend, knowing you put in enough hours. Or you'd like to have documentation to give to your manager for the hours put in. <br/>
                DoTime hopes to be able to provide it. <br/>
                </p>
                This is a project under construction. And we are working in small increments.<br/><br/>
                So far we have the following ready:
                <ul>
                    <li>User registration</li>
                    <li>Login</li>
                    <li>Work week hours settings</li>
                    <li>Registering Work from Home / Commuting to work</li>
                    <li><div class="badge badge-warning">new</div><span class="badge badge-success">v156</span> Showing total time worked this week, and how many hours out of the target number of hours for the day.</li>
                    <li><div class="badge badge-warning">new</div><span class="badge badge-success">v157</span> - added datepicker to do date navigation<img src="/images/datepicker_feature.png">
                    <li><div class="badge badge-warning">new</div><span class="badge badge-success">v159</span> Date chooser no longer allows choosing a date in the future. </li>
                    <li><div class="badge badge-warning">new</div><span class="badge badge-success">v166</span> Time worked for the week and day is now shown as percentage in a progress bar. </li>
                </ul>
                The following is work in progress:
                <ul>
                    <li>Time regisration form</li>
                    <li>Nice automatic update behind the scenes upon time registration</li>
                    <li>Week by week total work time</li>
                    <li>Month total time</li>
                    <li>Overtime on weekly and monthly basis</li>
                    <li>Putting hours in the bank</li>
                </ul>
                <p class="card-text">
                    We are getting there slowly, but surely.
                    The project is on <a href="https://www.github.com/simcax/dotime">Github</a>
                </p>
            </p>
            
            </div>
        </div>
        </div>
    </div>
</div>

{% endblock %} 

app/templates/loggedin.html
{% extends "header.html" %}
{% block profile %}
<div class="container h-100">
    <div class="card mb-3 justify-content-center" style="max-width: 540px;">
        <div class="row g-0 justify-content-center">
        <div class="col-md-4">
            <img src="/images/welcome.jpg" class="brand_logo" alt="Logo" height="200" width="200">
            <p class="card-text"><small class="text-muted">Photo by <a href="https://unsplash.com/@aaronburden?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Aaron Burden</a> on <a href="https://unsplash.com/s/photos/welcome-back?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a></small></p>
        </div>
        <div class="col-md-8 justify-content-center">
            <div class="card-body justify-content-center">
            <h5 class="card-title">You are logged in.</h5>
            <p class="card-text">Welcome. Good to see you. Let's log some time.</p>
            </div>
        </div>
        </div>
    </div>
</div>

{% endblock %} 

app/templates/login.html
{% block login %}
{% if g.user %}
  Hi {{ g.user.email }}!
{% else %}
<form action="/auth/login" method="POST" class="form-inline"> 
    <div class="form-group">
      
      <div class="input-group mb-3">
        <div class="input-group-append">
          <span class="input-group-text"><i class="fas fa-user"></i></span>
        </div>
        <input type="text" class="form-control input_user" id="email" placeholder="Email" name="email">
      </div>
    
      <div class="input-group mb-3">
        <div class="input-group-append">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
        <input type="password" class="form-control" id="password" placeholder="Password" name="password">
      </div>
    </div>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <div class="input-group-text">
          <input type="checkbox" name="rememberme" id="rememberme">&nbsp;Remember Me
        </div>
      </div>
    </div>
    {% if loginFailed %}
        <div class="alert-danger" role="alert">Login Failed!</div>
    {% endif %}
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        
          <input type="submit" class="btn btn-dark" name="submit" value="Login">
        
      </div>
    </div>
    
  </form>
{% endif %}
{% endblock %} 

app/templates/loginonly.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/@popperjs/core@2"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/css/background.css">
  <title>Login</title>
</head>
<body>
<br/>
<div class="container">
    <div class="d-flex justify-content-center">
        <span class="bg-light border p-3 border-dark rounded ">
        <div class="user_card ">
            <div class="d-flex justify-content-center">
                <div class="brand_logo_container">
                    <img src="{{ url_for('static',filename='images/dotime_logo.png') }}" class="brand_logo p-2" alt="Logo" height="159" width="239">
                </div>
            </div>
            <div class="d-flex justify-content-center form_container bg-light ">
                <form  method="POST" action="/auth/login">
                    <input type="hidden" name="next" value="{{ request.args.get('next','') }}">
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% set real_color_class="success" %}
                            {% if color_class == "danger" %}
                                {% set real_color_class="danger" %}
                            {% endif %}
                        <div class="form-group alert alert-{{ real_color_class }}" role="alert">
                            {% for message in messages %}
                            {{ message }}
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% endwith %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="email" class="form-control input_user" value="" placeholder="email">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" name="password" class="form-control input_pass" value="" placeholder="password">
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="customControlInline">
                            <label class="custom-control-label" for="customControlInline">Remember me</label>
                        </div>
                    </div>
  
                        
                    
                <div class="d-flex justify-content-center mt-3 login_container">
                 <button type="submit" name="button" class="btn btn-dark">Login</button>
               </div>
               
                </form>
            </div>
    
            <div class="mt-4 bg-light">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="/profile/create" class="ml-2">Sign Up</a>
                </div>
                <div class="d-flex justify-content-center links">
                    <a href="#">Forgot your password?</a>
                </div>
            </div>
        </div>
        </span>
    </div>
</div>
</body>

app/templates/profile_created.html
{% extends "header.html" %}
{% block profile %}
<div class="container-sm align-items-center">
    <div class="card" style="width: 18rem;">
        <img src="/images/hello.jpg" class="card-img-top" alt="hello and Welcome">
        <figcaption class="blockquote-footer">Photo by <a href="https://unsplash.com/@drew_beamer?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Drew Beamer</a> on <a href="https://unsplash.com/s/photos/welcome?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
        </figcaption>
        <div class="card-body">
        <h5 class="card-title">Welcome {{ user.username }}</h5>
        <p class="card-text">Nice you wanted to try out DoTime! Your profile was created.<br>Here some explenation will come as the site progresses. Right now we only have login and profile creation up and running.</p>
        <a href="#" class="btn btn-primary">Go back to the frontpage.</a>
        </div>
    </div>
</div>
{% endblock %} 


  

app/templates/profile_creation_failed.html
{% extends "header.html" %}
{% block profile %}
<div class="container-sm align-items-center">
    <div class="card" style="width: 18rem;">
        <img src="/images/oops.jpg" class="card-img-top" alt="hello and Welcome">
        <figcaption class="blockquote-footer">Photo by <a href="https://unsplash.com/@krakenimages?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">krakenimages</a> on <a href="https://unsplash.com/s/photos/mistake?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
        </figcaption>
        <div class="card-body">
        <h5 class="card-title">That didn't work out</h5>
        <p class="card-text">Sorry, we couldn't create your profile.</p>
        <a href="{{ url_for('profile_blueprint.create_profile') }}" class="btn btn-primary">Try again?</a>
        </div>
    </div>
</div>
{% endblock %} 


  

app/templates/profile_me.html
{% extends "header.html" %}
{% block profile %}
<div class="container">
    <br/><br/><br/>
    <div class="card" style="width: 50rem;">
        <div class="card-body">
            <h5 class="card-title">Profile Information</h5>
            <form action="/profile/update" method="POST"> 
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" placeholder="Username" name="profileUsername" value="{{ userdata['username'] }}" readonly>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label for="email">Email address</label>
                        <input type="text" class="form-control" id="email" placeholder="Email" name="profileEmail" value="{{ userdata['email'] }}">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">

                    </div>
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="form-group alert alert-danger" role="alert">
                        {% for message in messages %}
                        {{ message }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% endwith %}
                    <div class="col">
                        <button type="submit" class="btn btn-success float-right" >Update Profile</button>    
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} 

app/templates/profile_settings.html
{% extends "header.html" %}
{% block profile %}
<div class="container">
    <br/><br/><br/>
    <div class="card" style="width: 50rem;">
        <div class="card-body">
            <h5 class="card-title">Profile Information</h5>
            <form action="/profile/settings" method="POST"> 
                <div class="form-group">
                    

                    <label for="workdayLengthHours">Workday length</label>
                    <p>How many hours do you work on these days?</p>
                    <div class="form-group">
                        
                    {% for i in range(1,8) %}
                    {% set istr = i | string() %}
                    {% set minutes_key = 'workdayLength'+istr+'Minutes' %}
                    {% set minutes = workday_lengths[minutes_key] %}
                    {% set hours_key = 'workdayLength'+istr+'Hour' %}
                    {% set hours = workday_lengths[hours_key] %}
                    
                            <div class="col-14">
                                <label for="{{ hours_key }}">{{ workday_lengths['workdayName'+istr] }}</label>
                            </div>
                        
                        <div class="row">
                            <div class="col">
                                
                                <input type="number" minlength="1" maxlength="2" size="2" class="form-control" id="{{ hours_key }}" name="{{ hours_key }}" value="{{ hours }}">
                            </div>
                            <div class="col">
                                <input type="number" minlength="1" maxlength="2" size="2" class="form-control" id="{{ minutes_key }}" name="{{ minutes_key }}" value="{{ minutes }}">
                            </div>
                        </div>
                    
                    {% endfor %}
                
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">

                    </div>
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="form-group alert alert-danger" role="alert">
                        {% for message in messages %}
                        {{ message }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% endwith %}
                    <div class="col">
                        <button type="submit" class="btn btn-success float-right" >Update Settings</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} 

app/templates/test1_entertime.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <!--
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/timepicker@1.13.18/jquery.timepicker.js">
        <script src="https://cdn.jsdelivr.net/npm/timepicker@1.13.18/jquery.timepicker.min.css"></script>
        -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
        <script lang="javascript">        
            $(document).ready(function(){
                const roundTo = roundTo => x => Math.round(x / roundTo) * roundTo;    
                const roundDownTo = roundTo => x => Math.floor(x / roundTo) * roundTo;
                const roundUpTo = roundTo => x => Math.ceil(x / roundTo) * roundTo;

                const roundTo5Minutes = roundTo(1000 * 60 * 5);
                const roundDownTo5Minutes = roundDownTo(1000 * 60 * 5);
                const roundUpTo5Minutes = roundUpTo(1000 * 60 * 5);
                console.log(roundTo5Minutes(Date.now()));
                function prettyDate2(time) {
                    var date = new Date(parseInt(time));
                    return date.toLocaleTimeString(navigator.language, {
                        hour: '2-digit',
                        minute:'2-digit'
                    });
                }
                var current_time = prettyDate2(roundTo5Minutes(Date.now()))
                console.log( "document loaded"+current_time );
                $('.from_time')
                .timepicker({
                    timeFormat: 'HH:mm',
                    interval: 5,
                    minTime: '00:00',
                    defaultTime: current_time,
                    dynamic: true,
                    dropdown: true,
                    scrollbar: true,
                    change: function(time) {
                        // the input field
                        var from_time = $("input[name='from_time']").val();
                        console.log("From time:"+from_time);
                        $('#time_end').timepicker('option', 'minTime', from_time);
                        if ($('#time_end').val() && $('#time_end').val() < from_time) {
                            $('#time_end').timepicker('setTime', from_time);
                        }
                    
                }
                })
                .on('selectTime', function() {  
                    var from_time = $("input[name='from_time']").val();
                    console.log("From time:"+from_time);
                    $('#time_end').timepicker('option', 'minTime', from_time);
                    if ($('#time_end').val() && $('#time_end').val() < from_time) {
                        $('#time_end').timepicker('setTime', from_time);
                    }
                });
                $('.time_end').timepicker({
                    timeFormat: 'HH:mm',
                    interval: 5,
                    defaultTime: current_time,
                    dynamic: true,
                    dropdown: true,
                    scrollbar: true
                });
                
            });
    
        </script>
    </head> 
    <body>
        <input id="from_time" name="from_time" class="from_time text-center" jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown">
        <input id="time_end" class="time_end text-center" jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown">
    </body>
</html>